            - name: Check LoC
  # You may pin to the exact commit or the version.
  # uses: Berke-Ates/LoC@721f3f71f0a891ed7b318344bb6f8e48237b327d
  uses: Berke-Ates/LoC@v1.4
  with:
    # Folder to scan
    folder: # optional, default is ./
    # Files to exclude
    exclude: # optional, default is 
    # Max lines of code per file
    max-lines: # optional, default is 1000
          
